# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Find the letter that was added in t.
#
# Example:
#
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.

s = "abcd"
t = "abcde"

while len(t) > 1 and s[0] == t[0] and s[-1] == t[-1]:
    s = s[1:-1]
    t = t[1:-1]

if len(t) is 1:
    print(f"Letter added was: {t}:")
elif s[0] != t[0]:
    print(f"Letter added was: {t[0]}")
else:
    print(f"Letter added was: {t[-1]}")